kind: Service
apiVersion: v1
metadata:
  #Service name
  name: restaurandom
spec:
  selector:
    app: restaurandom-1541533424949
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
